const BOOK_COMPONENT_ADDED = 'BOOK_COMPONENT_ADDED'
const BOOK_COMPONENT_DELETED = 'BOOK_COMPONENT_DELETED'
const BOOK_COMPONENT_WORKFLOW_UPDATED = 'BOOK_COMPONENT_WORKFLOW_UPDATED'
const BOOK_COMPONENT_PAGINATION_UPDATED = 'BOOK_COMPONENT_PAGINATION_UPDATED'
const BOOK_COMPONENT_TRACK_CHANGES_UPDATED =
  'BOOK_COMPONENT_TRACK_CHANGES_UPDATED'
const BOOK_COMPONENT_TITLE_UPDATED = 'BOOK_COMPONENT_TITLE_UPDATED'
const BOOK_COMPONENT_CONTENT_UPDATED = 'BOOK_COMPONENT_CONTENT_UPDATED'
const BOOK_COMPONENT_UPLOADING_UPDATED = 'BOOK_COMPONENT_UPLOADING_UPDATED'

module.exports = {
  BOOK_COMPONENT_ADDED,
  BOOK_COMPONENT_DELETED,
  BOOK_COMPONENT_WORKFLOW_UPDATED,
  BOOK_COMPONENT_PAGINATION_UPDATED,
  BOOK_COMPONENT_TRACK_CHANGES_UPDATED,
  BOOK_COMPONENT_TITLE_UPDATED,
  BOOK_COMPONENT_CONTENT_UPDATED,
  BOOK_COMPONENT_UPLOADING_UPDATED,
}
