FROM node:12

RUN apt-get update \ 
    && apt-get upgrade -y \
    && apt-get install -y ranger vim

WORKDIR /home/node/app

COPY package.json .
COPY server/vivliostyle ./server/vivliostyle
COPY yarn.lock .

RUN chown -R node:node .
USER node


RUN yarn install
# RUN yarn cache clean
COPY --chown=node:node . .

