const bookComponent = require('./bookComponent')
const objectStorage = require('./objectStorage')
const file = require('./file')
const services = require('./services')

module.exports = {
  useCaseAddBookComponent: bookComponent.addBookComponent,
  useCaseUpdateBookComponentContent: bookComponent.updateContent,
  useCaseToggleIncludeInTOC: bookComponent.toggleIncludeInTOC,
  useCaseUpdateComponentType: bookComponent.updateComponentType,
  useCaseUpdateUploading: bookComponent.updateUploading,
  useCaseUpdateTrackChanges: bookComponent.updateTrackChanges,
  useCaseUpdatePagination: bookComponent.updatePagination,
  useCaseLockBookComponent: bookComponent.lockBookComponent,
  useCaseUnlockBookComponent: bookComponent.unlockBookComponent,
  useCaseUpdateWorkflowState: bookComponent.updateWorkflowState,
  useCaseDeleteBookComponent: bookComponent.deleteBookComponent,
  useCaseRenameBookComponent: bookComponent.renameBookComponent,
  useCaseSignURL: objectStorage.signURL,
  useCaseUploadFile: objectStorage.uploadFile,
  useCaseDeleteRemoteFiles: objectStorage.deleteFiles,
  useCaseListRemoteFiles: objectStorage.listFiles,
  useCaseGetRemoteFileInfo: objectStorage.getFileInfo,
  useCaseFetchRemoteFileLocally: objectStorage.locallyDownloadFile,
  useCaseCreateFile: file.createFile,
  useCaseUpdateFile: file.updateFile,
  useCaseUpdateFiles: file.updateFiles,
  useCaseGetEntityFiles: file.getEntityFiles,
  useCaseGetFiles: file.getFiles,
  useCaseGetSpecificFiles: file.getSpecificFiles,
  useCaseGetFile: file.getFile,
  useCaseDeleteDBFile: file.deleteFile,
  useCaseDeleteDBFiles: file.deleteFiles,
  useCaseGetFileURL: file.getFileURL,
  useCaseGetContentFiles: file.getContentFiles,
  useCaseIsFileInUse: file.isFileInUse,
  useCaseEPUBChecker: services.epubcheckerHandler,
  useCaseICML: services.icmlHandler,
  useCaseXSweet: services.xsweetHandler,
  useCasePDF: services.pdfHandler,
  useCaseGetPreviewerLink: services.pagedPreviewerLinkHandler,
}
