const BOOK_CREATED = 'BOOK_CREATED'
const BOOK_DELETED = 'BOOK_DELETED'
const BOOK_RENAMED = 'BOOK_RENAMED'
const BOOK_ARCHIVED = 'BOOK_ARCHIVED'
const BOOK_METADATA_UPDATED = 'BOOK_METADATA_UPDATED'
const BOOK_RUNNING_HEADERS_UPDATED = 'BOOK_RUNNING_HEADERS_UPDATED'

module.exports = {
  BOOK_CREATED,
  BOOK_DELETED,
  BOOK_RENAMED,
  BOOK_ARCHIVED,
  BOOK_METADATA_UPDATED,
  BOOK_RUNNING_HEADERS_UPDATED,
}
