const COLLECTION_ADDED = 'COLLECTION_ADDED'
const COLLECTION_DELETED = 'COLLECTION_DELETED'
const COLLECTION_RENAMED = 'COLLECTION_RENAMED'

export { COLLECTION_ADDED, COLLECTION_DELETED, COLLECTION_RENAMED }
