const { isAuthenticated } = require('@coko/server/authorization')

const permissions = {
  Query: {
    user: isAuthenticated,
    currentUser: isAuthenticated,
    users: isAuthenticated,
    team: isAuthenticated,
    teams: isAuthenticated,
    getWaxRules: isAuthenticated,
    getDashBoardRules: isAuthenticated,
    getBookBuilderRules: isAuthenticated,
    getApplicationParameters: isAuthenticated,
    getBook: isAuthenticated,
    getPagedPreviewerLink: isAuthenticated,
    getBookComponent: isAuthenticated,
    getBookCollection: isAuthenticated,
    getBookCollections: isAuthenticated,
    getCustomTags: isAuthenticated,
    getExportScripts: isAuthenticated,
    getFiles: isAuthenticated,
    getFile: isAuthenticated,
    getSignedURL: isAuthenticated,
    getEntityFiles: isAuthenticated,
    getSpecificFiles: isAuthenticated,
    getBookTeams: isAuthenticated,
    getGlobalTeams: isAuthenticated,
    getTemplates: isAuthenticated,
    getTemplate: isAuthenticated,
  },
  Mutation: {
    upload: isAuthenticated,
    deleteUser: isAuthenticated,
    updateUser: isAuthenticated,
    createTeam: isAuthenticated,
    deleteTeam: isAuthenticated,
    updateTeam: isAuthenticated,
    updateApplicationParameters: isAuthenticated,
    archiveBook: isAuthenticated,
    createBook: isAuthenticated,
    renameBook: isAuthenticated,
    deleteBook: isAuthenticated,
    updateMetadata: isAuthenticated,
    updateRunningHeaders: isAuthenticated,
    exportBook: isAuthenticated,
    ingestWordFile: isAuthenticated,
    addBookComponent: isAuthenticated,
    renameBookComponent: isAuthenticated,
    deleteBookComponent: isAuthenticated,
    archiveBookComponent: isAuthenticated,
    updateWorkflowState: isAuthenticated,
    updatePagination: isAuthenticated,
    unlockBookComponent: isAuthenticated,
    lockBookComponent: isAuthenticated,
    updateTrackChanges: isAuthenticated,
    updateContent: isAuthenticated,
    updateComponentType: isAuthenticated,
    updateUploading: isAuthenticated,
    toggleIncludeInTOC: isAuthenticated,
    createBookCollection: isAuthenticated,
    addCustomTag: isAuthenticated,
    updateCustomTag: isAuthenticated,
    updateBookComponentOrder: isAuthenticated,
    uploadFiles: isAuthenticated,
    updateFile: isAuthenticated,
    deleteFiles: isAuthenticated,
    updateTeamMembers: isAuthenticated,
    searchForUsers: isAuthenticated,
    updateEditoriaUser: isAuthenticated,
    updatePassword: isAuthenticated,
    updatePersonalInformation: isAuthenticated,
    updateUsername: isAuthenticated,
    createTemplate: isAuthenticated,
    cloneTemplate: isAuthenticated,
    updateTemplate: isAuthenticated,
    updateTemplateCSSFile: isAuthenticated,
    deleteTemplate: isAuthenticated,
  },
}

module.exports = permissions
