const BOOK_CREATED = 'BOOK_CREATED'
const BOOK_DELETED = 'BOOK_DELETED'
const BOOK_RENAMED = 'BOOK_RENAMED'
const BOOK_ARCHIVED = 'BOOK_ARCHIVED'

module.exports = { BOOK_CREATED, BOOK_DELETED, BOOK_RENAMED, BOOK_ARCHIVED }
