const BOOK_COMPONENT_ADDED = 'BOOK_COMPONENT_ADDED'
const BOOK_COMPONENT_DELETED = 'BOOK_COMPONENT_DELETED'
const BOOK_COMPONENT_WORKFLOW_UPDATED = 'BOOK_COMPONENT_WORKFLOW_UPDATED'
const BOOK_COMPONENT_PAGINATION_UPDATED = 'BOOK_COMPONENT_PAGINATION_UPDATED'
const BOOK_COMPONENT_TRACK_CHANGES_UPDATED =
  'BOOK_COMPONENT_TRACK_CHANGES_UPDATED'
const BOOK_COMPONENT_TITLE_UPDATED = 'BOOK_COMPONENT_TITLE_UPDATED'
const BOOK_COMPONENT_CONTENT_UPDATED = 'BOOK_COMPONENT_CONTENT_UPDATED'
const BOOK_COMPONENT_UPLOADING_UPDATED = 'BOOK_COMPONENT_UPLOADING_UPDATED'
const BOOK_COMPONENT_LOCK_UPDATED = 'BOOK_COMPONENT_LOCK_UPDATED'
const BOOK_COMPONENT_TYPE_UPDATED = 'BOOK_COMPONENT_TYPE_UPDATED'
const BOOK_COMPONENT_TOC_UPDATED = 'BOOK_COMPONENT_TOC_UPDATED'
const BOOK_COMPONENT_UNLOCKED_BY_ADMIN = 'BOOK_COMPONENT_UNLOCKED_BY_ADMIN'

module.exports = {
  BOOK_COMPONENT_ADDED,
  BOOK_COMPONENT_DELETED,
  BOOK_COMPONENT_WORKFLOW_UPDATED,
  BOOK_COMPONENT_PAGINATION_UPDATED,
  BOOK_COMPONENT_TRACK_CHANGES_UPDATED,
  BOOK_COMPONENT_TITLE_UPDATED,
  BOOK_COMPONENT_CONTENT_UPDATED,
  BOOK_COMPONENT_UPLOADING_UPDATED,
  BOOK_COMPONENT_LOCK_UPDATED,
  BOOK_COMPONENT_TYPE_UPDATED,
  BOOK_COMPONENT_TOC_UPDATED,
  BOOK_COMPONENT_UNLOCKED_BY_ADMIN,
}
